[package]
name = "orrethd"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde_json = { workspace = true }
ureq = { version = "2", features = ["json"] }
orreth-node = { path = "../orreth-node" }
orreth-store = { path = "../orreth-store" }
